services:
  db:
    image: pgvector/pgvector:pg18
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build: ./api/
    container_name: rag-api
    volumes:
      - ./api/app:/app
    ports:
      - '8000:8000'
    env_file: .env
    environment:
      DB_URI: postgresql+psycopg://postgres:password@db:5432/postgres
    depends_on:
      - db

volumes:
  pgdata:

networks:
  default: